# Generated by Django 3.1.7 on 2021-03-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField(max_length=20)),
                ('mobile', models.IntegerField(max_length=10)),
                ('dob', models.DateField(verbose_name='date of birth')),
            ],
        ),
    ]
