# Generated by Django 3.1.7 on 2021-03-25 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0002_auto_20210325_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
