# Generated by Django 3.1.7 on 2021-03-25 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0003_auto_20210325_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Reg',
        ),
    ]
