# Generated by Django 3.1.7 on 2021-03-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0004_auto_20210325_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.TextField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('dob', models.DateField(verbose_name='date of birth')),
            ],
        ),
    ]
