# Generated by Django 3.1.7 on 2021-03-25 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticator', '0005_newreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewReg',
        ),
    ]
